apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      config.kubernetes.io/local-config: "true"
  spec:
    replicas: 2
- kind: Service
  metadata:
    labels:
      config.kubernetes.io/local-config: "true"
functionConfig:
  apiVersion: krm.kcl.dev/v1alpha1
  kind: KCLRun
  spec:
    params:
      requires:
        - key: config.kubernetes.io/local-config
          # Optional: If specified, a regular expression the annotation's value must match.
          allowedRegex: "true"
    source: oci://docker.io/kcllang/required-labels
